[package]
name = "tetratest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra = "0.7.0-alpha1"
lazy_static = "1.4.0"
pathfinding = "3.0.6"
hecs = "0.7.5"
itertools = "0.10.3"
